# @package _global_
defaults:
  - superhuman_numeric_combat
  - _self_
rl:
  ppo:
    policy_kwargs:
      features_extractor_class: soku_rl.rl.address_invariant_features.AddressInvariantCombatFeatures
